# -*- coding: utf-8 -*-
"""q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11OZkp6RdAYxQeAk_O1F10lAC_jxrPJ3F
"""

"""Q 1.1"""
def rev_complement(seq):
    comp = {"A" : "T", "T" : "A", "G" : "C", "C" : "G"}
    rev_comp = ""
    for base in seq[::-1]:
      if base in comp:
        rev_comp += comp[base]
    return rev_comp

"""Q 1.2"""
def gc_content(seq):
  counter = 0
  for base in seq:
    if base == 'C' or base =='G':
      counter+=1
  return (counter/len(seq))

"""Q 1.3"""
def find_motif_freq(motif, seq):
    return seq.count(motif)

"""Q 1.4"""
def find_binding_site(bind, seq):
    bind = rev_complement(bind)
    try:
        return seq.index(bind)
    except:
        return -1

if __name__ == '__main__':
    print(rev_complement("ATGTACTAGCTA"))
    print(gc_content("ATCGACTCGAGTCGTACGTTCACG"))
    print(find_motif_freq("ATC", "ACTGACTATCGTCAGTCGATCTAATCCTG"))
    print(find_binding_site("ATGC", "ACTCGACTCAGCATCATACGGACTC"))
    pass